### PR TITLE
fix: Perform watches on a per-object basis instead of globally on the kind

### LINKED ISSUE #103: GitlabComment posts empty comment
I am experimenting with template-controller for dynamic review environments. While it seems to solve my basic usages, I am experiencing some issues with the GitLab integration.

For my last MR, template-controller posted an empty comment, and I don't understand why. Details below.

image

Source:

````
<!-- template-controller-gitlab-comment "05697033-2f1f-47e7-82b3-ceb5bea5117f" "stas-review/stas-rev-gitlab-eso" -->
````

Resources:

````yaml
apiVersion: templates.kluctl.io/v1alpha1
kind: GitlabComment
metadata:
  creationTimestamp: '2024-07-11T06:44:30Z'
  generation: 1
  managedFields:
    - apiVersion: templates.kluctl.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:comment':
            'f:source':
              'f:textTemplate':
                'f:name': {}
          'f:gitlab':
            'f:api': {}
            'f:mergeRequestId': {}
            'f:project': {}
            'f:tokenRef':
              'f:key': {}
              'f:secretName': {}
      manager: template-controller
      operation: Apply
      time: '2024-07-11T06:44:30Z'
    - apiVersion: templates.kluctl.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:lastPostedBodyHash': {}
          'f:noteId': {}
      manager: template-controller
      operation: Update
      subresource: status
      time: '2024-07-11T06:44:30Z'
  name: stas-rev-gitlab-eso
  namespace: stas-review
  resourceVersion: '1180343145'
  uid: 55bd81d4-066b-467e-9730-303938614d89
spec:
  comment:
    source:
      textTemplate:
        name: stas-rev-gitlab-eso
  gitlab:
    api: <REDACTED>
    mergeRequestId: '30'
    project: stas/stas-tenant
    tokenRef:
      key: token
      secretName: stas-tenant-gitlab
  suspend: false
status:
  conditions:
    - lastTransitionTime: '2024-07-11T06:44:30Z'
      message: Success
      observedGeneration: 1
      reason: Success
      status: 'True'
      type: Ready
  lastPostedBodyHash: 10c4eaafc08fbd6659b0429ec44d53dcff070a98783fd118d549556f73021da7
  noteId: '1825991'
---
apiVersion: templates.kluctl.io/v1alpha1
kind: TextTemplate
metadata:
  creationTimestamp: '2024-07-11T06:44:30Z'
  generation: 1
  managedFields:
    - apiVersion: templates.kluctl.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:inputs': {}
          'f:serviceAccountName': {}
          'f:templateRef':
            'f:configMap':
              'f:key': {}
              'f:name': {}
      manager: template-controller
      operation: Apply
      time: '2024-07-11T06:44:30Z'
    - apiVersion: templates.kluctl.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:result': {}
      manager: template-controller
      operation: Update
      subresource: status
      time: '2024-07-11T06:44:30Z'
  name: stas-rev-gitlab-eso
  namespace: stas-review
  resourceVersion: '1180343133'
  uid: bc94f308-b242-412c-a9ed-11bdd3100035
spec:
  inputs:
    - name: kustomization
      object:
        ref:
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          name: stas-rev-gitlab-eso
  serviceAccountName: gitops-reconciler
  suspend: false
  templateRef:
    configMap:
      key: merge-request-comment.md.jinja
      name: gitlab-template
status:
  conditions:
    - lastTransitionTime: '2024-07-11T06:44:30Z'
      message: Success
      observedGeneration: 1
      reason: Success
      status: 'True'
      type: Ready
  result: |+
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gitlab-template
  namespace: stas-review
  uid: f8a581f5-12f3-438b-92b8-843b6298e34d
  resourceVersion: '1178464889'
  creationTimestamp: '2024-07-10T07:32:16Z'
  labels:
    kustomize.toolkit.fluxcd.io/name: stas-review
    kustomize.toolkit.fluxcd.io/namespace: stas
  managedFields:
    - manager: kustomize-controller
      operation: Apply
      apiVersion: v1
      time: '2024-07-10T07:32:16Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:merge-request-comment.md.jinja': {}
        'f:metadata':
          'f:labels':
            'f:kustomize.toolkit.fluxcd.io/name': {}
            'f:kustomize.toolkit.fluxcd.io/namespace': {}
data:
  merge-request-comment.md.jinja: |
    {% set conditionsByType = dict(get_var("inputs.kustomization.status.conditions", []) | groupby(attribute="type")) %}

    {% if "Ready" in conditionsByType and conditionsByType["Ready"] %}
    {% if conditionsByType["Ready"][0].status == "True" %}
    # :robot: Kustomization is ready! :thumbsup:
    {% else %}
    # :robot: Kustomization is NOT ready! :thumbsdown:<br><br>
    Message from controller: {{ conditionsByType["Ready"][0].message }}
    {% endif %}
    {% endif %}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  creationTimestamp: '2024-07-11T06:44:30Z'
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  managedFields:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:sourceRef':
            'f:kind': {}
            'f:name': {}
          'f:wait': {}
          'f:timeout': {}
          'f:prune': {}
          'f:targetNamespace': {}
          'f:force': {}
          'f:interval': {}
          'f:path': {}
          'f:retryInterval': {}
      manager: template-controller
      operation: Apply
      time: '2024-07-11T06:44:30Z'
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"finalizers.fluxcd.io"': {}
      manager: gotk-kustomize-controller
      operation: Update
      time: '2024-07-11T06:44:30Z'
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions': {}
          'f:inventory':
            .: {}
            'f:entries': {}
          'f:lastAppliedRevision': {}
          'f:lastAttemptedRevision': {}
          'f:observedGeneration': {}
      manager: gotk-kustomize-controller
      operation: Update
      subresource: status
      time: '2024-07-11T06:45:01Z'
  name: stas-rev-gitlab-eso
  namespace: stas-review
  resourceVersion: '1180343831'
  uid: 021f4a96-fa17-4142-9682-185730fadde4
spec:
  timeout: 3m0s
  path: ./review
  interval: 60m0s
  targetNamespace: stas-rev-gitlab-eso
  prune: true
  force: false
  retryInterval: 2m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: stas-rev-gitlab-eso
status:
  conditions:
    - lastTransitionTime: '2024-07-11T06:45:01Z'
      message: 'Applied revision: gitlab-eso@sha1:93d0eafabcb51fff33ffafc65c2e2fd47507a173'
      observedGeneration: 1
      reason: ReconciliationSucceeded
      status: 'True'
      type: Ready
    - lastTransitionTime: '2024-07-11T06:45:01Z'
      message: Health check passed in 27.669123ms
      observedGeneration: 1
      reason: Succeeded
      status: 'True'
      type: Healthy
  inventory:
    entries:
      - id: stas-rev-gitlab-eso_foo-fck7mbk8d4__Secret
        v: v1
  lastAppliedRevision: 'gitlab-eso@sha1:93d0eafabcb51fff33ffafc65c2e2fd47507a173'
  lastAttemptedRevision: 'gitlab-eso@sha1:93d0eafabcb51fff33ffafc65c2e2fd47507a173'
  observedGeneration: 1
````

### PR DESCRIPTION
**Pull request by codablock**
This PR switches from global per-kind watches to per-object watches. Each ObjectTemplate/TextTemplate uses its own instance of `watchesForTemplate` to keep track of watches.

This also means that impersonation is from now on used for watches.

Fixes #103 and #38

### CODE REVIEW

File: controllers/texttemplate_controller.go [hunk 1]
```diff
@@ -189,37 +206,22 @@ func (r *TextTemplateReconciler) doReconcile(ctx context.Context, tt *templatesv
 	return nil
 }
 
+func (r *TextTemplateReconciler) finalize(ctx context.Context, obj *templatesv1alpha1.TextTemplate) (ctrl.Result, error) {
+	r.watchesUtil.removeWatchesForTemplate(client.ObjectKeyFromObject(obj))
+
+	// Remove our finalizer from the list and update it
+	controllerutil.RemoveFinalizer(obj, templatesv1alpha1.TextTemplateFinalizer)
+	if err := r.Update(ctx, obj, client.FieldOwner(r.FieldManager)); err != nil {
```
Comment (erikgb) [inline controllers/texttemplate_controller.go:214]: Is it possible to remove the finalizer with a patch? You add it with a patch, and I am unsure it you can remove it with an update. You should also check that the finalizer is removed when the object is "deleted" in tests. It is crucial that finalizers work! I try to avoid finalizers, but in this case I think they are required - at least for now.

**Review by erikgb — COMMENTED** [review]
This looks great! I would have preferred to avoid the finalizers and mutexes. I think controller-runtime might have support for dynamic watches in later releases, but I haven't tried it.

File: controllers/base_template_reconciler.go [hunk 2]
```diff
@@ -7,78 +7,45 @@ import (
...
-	mutex        sync.Mutex
+	controller controller.Controller
+
+	watchesUtil watchesUtil
+
+	mutex sync.Mutex
 }
 
-func (r *BaseTemplateReconciler) getClientForObjects(serviceAccountName string, objNamespace string) (client.Client, error) {
+func (r *BaseTemplateReconciler) getClientForObjects(serviceAccountName string, objNamespace string) (client.WithWatch, string, error) {
```
[the remark this answers is not in the document]
Comment (codablock) [reply controllers/base_template_reconciler.go]: Agree. After thinking more about this, I decided to use the defaulting of controller-runtime/controller-gen instead of manually defaulting here.

File: controllers/objecttemplate_controller.go [hunk 3]
```diff
@@ -55,9 +50,7 @@ type ObjectTemplateReconciler struct {
 //+kubebuilder:rbac:groups=templates.kluctl.io,resources=objecttemplates/status,verbs=get;update;patch
 //+kubebuilder:rbac:groups=templates.kluctl.io,resources=objecttemplates/finalizers,verbs=update
 //+kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,verbs=get;list;watch
```
[the remark this answers is not in the document]
Comment (codablock) [reply controllers/objecttemplate_controller.go]: Removed :+1:

File: controllers/objecttemplate_controller.go [hunk 4]
```diff
@@ -203,11 +184,25 @@ func (r *ObjectTemplateReconciler) doReconcile(ctx context.Context, rt *template
...
 
-	objClient, err := r.getClientForObjects(rt.Spec.ServiceAccountName, rt.GetNamespace())
+	objClient, saName, err := r.getClientForObjects(rt.Spec.ServiceAccountName, rt.GetNamespace())
 	if err != nil {
 		return err
 	}
 
+	wt := r.watchesUtil.getWatchesForTemplate(client.ObjectKeyFromObject(rt))
+	wt.setClient(objClient, saName)
+	newObjects := map[templatesv1alpha1.ObjectRef]bool{}
```
[the remark this answers is not in the document]
Comment (codablock) [reply controllers/objecttemplate_controller.go:193]: Changed to struct{} and while doing so fixed a crucial bug that got introduced accidentally. Would have been caught if tests for TextTemplate controller would have been present already ;) (on my TODO before next release)

File: controllers/texttemplate_controller.go (hunk 1 above)
Comment (codablock) [reply controllers/texttemplate_controller.go]: I switched to using patches now and added some simple testing for final removal, which implies proper removal of finalizers. I'll add more tests in regard to pruning (where finalizers are even more important) in a future PR.

File: api/v1alpha1/texttemplate_types.go [hunk 5]
```diff
@@ -20,16 +20,21 @@ import (
...
 	// +kubebuilder:default:=false
 	Suspend bool `json:"suspend"`
 
-	// The name of the Kubernetes service account to impersonate
-	// when reconciling this TextTemplate. If omitted, the "default" service account is used.
+	// ServiceAccountName specifies the name of the Kubernetes service account to impersonate
+	// when reconciling this TextTemplate. If omitted, the "default" service account is used
 	// +optional
+	// +kubebuilder:default:="default"
 	ServiceAccountName string `json:"serviceAccountName,omitempty"`
```
Comment (erikgb) [inline api/v1alpha1/texttemplate_types.go:38]:
```suggestion
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
```

Using a pointer here will make it possible to distinguish `""` (invalid) from unset. Optional fields should usually be represented with pointer in the Go API, ref. https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required

**Review by erikgb — APPROVED** [review]
LGTM, but easy to overlook details in a huge PR like this one! 🤠

File: api/v1alpha1/texttemplate_types.go (hunk 5 above)
Comment (codablock) [reply api/v1alpha1/texttemplate_types.go:38]: I wonder if this is really an optional field when defaulting is also in place. In the end, the field will always have a non-nil value. What do you think?

Comment (codablock) [reply api/v1alpha1/texttemplate_types.go:38]: FYI, I'll merge for now and then include this change in a new PR after it's clear what to do here.
